# Generated by Django 5.1.2 on 2024-11-13 14:38

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "image",
                    cloudinary.models.CloudinaryField(
                        blank=True,
                        default="default.webp",
                        max_length=255,
                        null=True,
                        verbose_name="image",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(db_index=True, default=False)),
                ("average_rating", models.FloatField(default=0)),
                ("total_ratings", models.PositiveIntegerField(default=0)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="posts_post_created_183a3b_idx"
                    ),
                    models.Index(
                        fields=["author", "is_approved"],
                        name="posts_post_author__3dfd36_idx",
                    ),
                    models.Index(
                        fields=["average_rating", "-created_at"],
                        name="posts_post_average_831ec7_idx",
                    ),
                    models.Index(fields=["title"], name="posts_post_title_e7697c_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_approved", True)),
                        fields=("title",),
                        name="unique_post_title_case_insensitive",
                    )
                ],
            },
        ),
    ]
