# Generated by Django 5.0.6 on 2024-10-02 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_unique_post_slug'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_post_slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
