# Generated by Django 5.0.6 on 2024-10-12 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_options_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_created_dadbfe_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_is_appr_aa7284_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_author__19d68b_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='posts_post_title_e7697c_idx',
        ),
    ]
