# Generated by Django 5.0.6 on 2024-10-13 13:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_options_and_more'),
        ('tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='tags.profiletag'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'created_at'], name='posts_post_author__d94160_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_approved'], name='posts_post_is_appr_aa7284_idx'),
        ),
    ]
