# Generated by Django 5.1.2 on 2024-11-05 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_name",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["profile_name"], name="profiles_pr_profile_350214_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(
                fields=["user", "profile_name"], name="profiles_pr_user_id_373b6c_idx"
            ),
        ),
    ]
