# Generated by Django 5.0.6 on 2024-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_profile_birth_date_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='popularity_score',
            field=models.FloatField(default=0),
        ),
    ]
