# Generated by Django 5.0.6 on 2024-10-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_profile_comment_count_profile_follower_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='comment_count',
        ),
        migrations.AlterField(
            model_name='profile',
            name='follower_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='popularity_score',
            field=models.FloatField(db_index=True, default=0),
        ),
    ]
