# Generated by Django 5.0.6 on 2024-10-13 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_remove_profile_comment_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag_count',
        ),
    ]
