# Generated by Django 5.0.6 on 2024-10-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_remove_profile_tag_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follower_count',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='following_count',
        ),
    ]
