# Generated by Django 5.0.6 on 2024-10-10 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_blacklistedaccesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlacklistedAccessToken',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_email',
        ),
        migrations.RemoveConstraint(
            model_name='customuser',
            name='unique_profile_name',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
