# Generated by Django 5.1.2 on 2024-11-13 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PopularityMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_posts", models.PositiveIntegerField(default=0)),
                ("total_ratings_received", models.PositiveIntegerField(default=0)),
                ("average_rating", models.FloatField(default=0.0)),
                ("engagement_score", models.FloatField(default=0.0)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="popularity_metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["-engagement_score"],
                        name="popularity__engagem_9386c1_idx",
                    ),
                    models.Index(
                        fields=["-average_rating"],
                        name="popularity__average_4d2406_idx",
                    ),
                ],
            },
        ),
    ]
