# Generated by Django 5.1.2 on 2024-10-15 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("popularity", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="popularitymetrics",
            index=models.Index(
                fields=["follower_count"], name="popularity__followe_165e47_idx"
            ),
        ),
    ]
